[webservers]
65.2.188.159 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-servers-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
3.110.204.42 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-servers-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
